// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF0-I3BqerU1RCwTZk9_z8ZwHxh6Tz6p4',
    appId: '1:512237921526:web:5b84396141525a57e878d7',
    messagingSenderId: '512237921526',
    projectId: 'instegram-aada7',
    authDomain: 'instegram-aada7.firebaseapp.com',
    storageBucket: 'instegram-aada7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDagitm8tTpWvUPcdOhdNrMlW-T6nKGBH8',
    appId: '1:512237921526:android:e9ba2e2652ecb9cbe878d7',
    messagingSenderId: '512237921526',
    projectId: 'instegram-aada7',
    storageBucket: 'instegram-aada7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2LT11onW2IoMYw-fowD8R-SzqgcH0oiA',
    appId: '1:512237921526:ios:ed6108ac1828b7f2e878d7',
    messagingSenderId: '512237921526',
    projectId: 'instegram-aada7',
    storageBucket: 'instegram-aada7.appspot.com',
    iosBundleId: 'com.example.instegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2LT11onW2IoMYw-fowD8R-SzqgcH0oiA',
    appId: '1:512237921526:ios:ed6108ac1828b7f2e878d7',
    messagingSenderId: '512237921526',
    projectId: 'instegram-aada7',
    storageBucket: 'instegram-aada7.appspot.com',
    iosBundleId: 'com.example.instegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF0-I3BqerU1RCwTZk9_z8ZwHxh6Tz6p4',
    appId: '1:512237921526:web:a46d44f3370869c8e878d7',
    messagingSenderId: '512237921526',
    projectId: 'instegram-aada7',
    authDomain: 'instegram-aada7.firebaseapp.com',
    storageBucket: 'instegram-aada7.appspot.com',
  );
}
